<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_CoverageFile" Id="{73269a4b-8b1b-45f3-8e19-bd0d3a8051c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CoverageFile EXTENDS FB_FileBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	writeBuffer();

	SUPER^();
	
]]></ST>
    </Implementation>
    <LineIds Name="FB_CoverageFile">
      <LineId Id="21" Count="1" />
      <LineId Id="17" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="19" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>