<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_CoverageFile" Id="{73269a4b-8b1b-45f3-8e19-bd0d3a8051c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CoverageFile EXTENDS FB_FileBase

]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	writeBuffer();

	SUPER^();
	
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>